### PR TITLE
Add SlashChat

### PR DESCRIPTION
**Pull request by jeredm**
Adding an example that is similar to SimpleChat, but it allows slash commands in the message. 
- Private Message: /pm client@yourcomputer your_message
- Exit: /exit
- All other / commands return invalid command
- The normal messaging as in SimpleChat will still work

### CODE REVIEW

**Comment by kblake** [comment]
Fun! Cool to see you diving into some Elixir!

Something to make all-out slash-worthy:
Get rid of the `{:all,` pattern match and do a slash command for that. `”/all helloworld”`

**Comment by jeredm** [comment]
I added the /all command and updated a few of my pattern matching techniques.

**Comment by kblake** [comment]
@jeredm This is looking good. Any last tweaks before I merge it?

**Comment by jeredm** [comment]
@kblake I think it is good to go.

**Pull request merged**
